(function(_ds){var window=this;var gV=function(a){var b=a.di;a=a.columns;let c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">';const d=a.length;for(let e=0;e<d;e++){const f=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.P(f.lm)+'" tabindex="0" track-type="nav" track-name="'+_ds.P(f.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.P(b)+'" track-metadata-module="secondary nav">'+_ds.O(f.text)+"</a></li>"}return(0,_ds.N)(c+"</ul></div>")},hV=
function(a){var b=a.di,c=a.href;a=a.text;return(0,_ds.N)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.P(_ds.S(c))+'" track-type="nav" track-name="'+_ds.P(a)+'" track-metadata-eventdetail="'+_ds.P(c)+'" track-metadata-position="nav - '+_ds.P(b)+'" track-metadata-module="secondary nav">'+_ds.O(a)+"</a></div>")};var iV=function(a){a.v=Array.from(a.querySelectorAll("tab"));let b=a.querySelector(".devsite-tabs-wrapper");if(!b){b=a.ownerDocument.createElement("div");b.classList.add("devsite-tabs-wrapper");a.appendChild(b);var c;null==(c=a.v)||c.forEach(e=>{let f;return null==(f=b)?void 0:f.appendChild(e)})}a.C=b;a.appendChild(b);if(!a.hasAttribute("no-overflow")){c=a.ownerDocument.createElement("tab");_ds.y(a,"overflow-tab","",c);var d=a.ownerDocument.createElement("a");_ds.Wg(d,"#");d.textContent="More";d.classList.add("devsite-icon");
d.classList.add("devsite-icon-arrow-drop-down");c.appendChild(d);a.h=c;d=a.ownerDocument.createElement("div");d.classList.add("devsite-tabs-overflow-menu");_ds.y(a,"scrollbars","",d);_ds.y(a,"hidden","",d);a.D=d;c.appendChild(d);b.appendChild(c)}},mV=function(a){let b;null==(b=a.v)||b.forEach(async(c,d)=>{if(await jV(c)){var e=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column")),f=c.querySelector(".devsite-tabs-dropdown"),g=c.querySelector("a");e.forEach((h,k)=>{_ds.y(a,"column-id",`tab-${d}-column-${k}`,
h)});e=e.map(h=>{const k=h.querySelector(".devsite-nav-title")||h.querySelector(".devsite-nav-item-title");return{lm:h.getAttribute("column-id"),text:null==k?void 0:k.textContent}});g&&(g=_ds.L(gV,{di:(g.textContent||"").toLowerCase().trim(),columns:e}),f&&(e=c.querySelector(".devsite-tabs-dropdown-content")))&&(f.insertBefore(g,e),f=c.querySelector(".dropdown-tabbed-menu a"),kV(c),a.eventHandler.listen(g,"click",h=>{h.preventDefault();const k=c.querySelector(".dropdown-tabbed-menu-button");h=h.target;
k&&h.tagName&&"a"===h.tagName.toLowerCase()&&!k.contains(h)&&lV(a,c,(null==h?void 0:h.getAttribute("column-id"))||"")}),f&&lV(a,c,f.getAttribute("column-id")||""))}})},nV=function(a,b){if(!b)return 0;const c=[];let d=b;for(;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.y(a,"render-hidden","",d),d=d.parentElement;a=_ds.Dk(b).width;for(const e of c)e.removeAttribute("render-hidden");return a},wV=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",()=>a.H.h());a.eventHandler.listen(a,
"click",c=>{if(!(c.shiftKey||c.ctrlKey||c.metaKey||c.altKey)){var d=c.target,e=oV(a,d);if(e)if(e===a.h)pV(a,c);else if(qV(a),d.classList.contains("devsite-tabs-dropdown-toggle"))c.preventDefault(),c.stopPropagation(),e.hasAttribute("dropdown--open")?rV(a):sV(a,e);else{var f;"A"===d.tagName?f=d:f=_ds.Yh(d,"A");var g=e.querySelector(".devsite-tabs-dropdown");if(g&&g.contains(d))f&&f.hasAttribute("href")||(c.preventDefault(),c.stopPropagation());else{if(c=a.K||a.querySelector("[active]"))c.removeAttribute("active"),
_ds.y(a,"aria-selected","false",c);_ds.y(a,"active","",e);_ds.y(a,"aria-selected","true",e);a.K=e;f&&f&&"#"!==f.href||a.H.h()}}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b="onpointermove"in window?"pointerover":"mouseover";const c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){for(const e of d)a.eventHandler.listen(e,"click",f=>{const g=f.target,h=oV(a,g),k=null==h?void 0:h.querySelector(".devsite-tabs-dropdown");
if(k){let l;(null==(l=a.h)?0:l.contains(g))||k.contains(g)||(f.preventDefault(),f.stopPropagation(),(null==h?0:h.hasAttribute("dropdown--open"))?rV(a):tV(a,f))}});a.eventHandler.listen(document.body,"click",e=>{a.C&&!a.C.contains(e.target)&&rV(a)})}else a.eventHandler.listen(a,b,e=>void uV(a,e)),a.eventHandler.listen(a,c,()=>void vV(a))}b=[...a.querySelectorAll(".devsite-tabs-close-button")];for(const c of b)a.eventHandler.listen(c,"click",()=>rV(a))},xV=function(a){_ds.y(a,"hidden","",a.h);if(!(a.v&&
3>a.v.length)){var b=nV(a,a);if(0!==b){var c,d=(null==(c=a.v)?void 0:c.slice())||[],e=0,f;d.forEach(k=>{k.parentNode!==a.C&&(f?f.parentNode&&f.parentNode.insertBefore(k,f.nextSibling):_ds.Gh(a.C,k,0));f=k;e+=nV(a,k)});if(!(e<=b)){c=a.J;var g;null==(g=a.h)||g.removeAttribute("hidden");(g=a.querySelector("[active]"))&&(c+=nV(a,g));for(var h;null==(h=d)?0:h.length;){const k=d.shift();if(k===g)continue;const l=nV(a,k||null);if(c+l<=b)c+=l;else{let m;null==(m=a.D)||m.appendChild(k)}}}}}},uV=async function(a,
b){(await _ds.u()).isTouchEnabled()||tV(a,b)},vV=async function(a){(await _ds.u()).isTouchEnabled()||rV(a,300)},rV=function(a,b=0){_ds.F(a.j);window.clearTimeout(a.G);const c=a.querySelector("tab[dropdown--open]");if(c){const d=c.querySelector(".devsite-tabs-dropdown");_ds.y(a,"dropdown-transition","",d);_ds.lk(a.j,d,_ds.Ve,()=>{null==d||d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.y(a,"hidden","",d)});a.G=window.setTimeout(()=>{c.removeAttribute("dropdown--open");
yV(a,c)},b)}else a.removeAttribute("dropdown--open");qV(a)},oV=function(a,b){for(;b&&b!==a;){if("TAB"===b.tagName.toUpperCase())return b;b=b.parentElement}return null},tV=function(a,b){const c=b.target,d=oV(a,c);if(d){let e;d===a.h||(null==(e=a.h)?0:e.contains(c))?pV(a,b):sV(a,d)}},pV=async function(a,b){b.preventDefault();b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));await _ds.Xi();if(!a.hasAttribute("overflow-menu--open")){b=await _ds.u();await b.whenReady();
if(b.isTouchEnabled()){const d=e=>{a.contains(e.target)||qV(a);_ds.mk(a.j,document.body,["devsite-close-overflow-tabs","click"],d)};a.j.listen(document.body,["devsite-close-overflow-tabs","click"],d)}var c;null==(c=a.D)||c.removeAttribute("hidden");_ds.y(a,"overflow-menu--open","")}},sV=async function(a,b){qV(a);if(b.hasAttribute("dropdown")){if(_ds.F(a.j),window.clearTimeout(a.G),!b.hasAttribute("dropdown--open")){(await _ds.u()).isTouchEnabled()&&_ds.lk(a.j,document.body,"click",g=>{a.contains(g.target)||
rV(a)});var c=a.querySelector("tab[dropdown--open]"),d=b.querySelector(".devsite-tabs-dropdown");if(d){d.removeAttribute("hidden");_ds.rk(d,"left","");var e=_ds.xh(window||window),f=Array.from(d.querySelectorAll(".devsite-tabs-dropdown-column"));if(!b.hasAttribute("dropdown-full")&&1<f.length){const g=[];f.forEach(k=>{g.push(k.scrollWidth)});const h=Math.max.apply(null,g);h*f.length<e.width?f.forEach(k=>{_ds.rk(k,"width",`${h}px`)}):_ds.y(a,"dropdown-full","",b)}f=d.getBoundingClientRect();b.hasAttribute("dropdown-full")?
_ds.rk(d,"left",`-${f.left}px`):(e=Math.min(f.left,f.left+f.width-e.width),0<e&&_ds.rk(d,"left",`-${e}px`));c?(c.removeAttribute("dropdown--open"),yV(a,c),c=c.querySelector(".devsite-tabs-dropdown"),null==c||c.removeAttribute("dropdown-transition"),_ds.y(a,"hidden","",c)):(_ds.y(a,"dropdown-transition","",d),_ds.lk(a.j,d,_ds.Ve,()=>d.removeAttribute("dropdown-transition")));window.requestAnimationFrame(()=>{_ds.y(a,"dropdown--open","");_ds.y(a,"dropdown--open","",b);yV(a,b)})}else c&&(c.removeAttribute("dropdown--open"),
yV(a,c))}}else rV(a)},yV=function(a,b){_ds.y(a,"aria-expanded",`${b.hasAttribute("dropdown--open")}`,b.querySelector(".devsite-tabs-dropdown-toggle"))},qV=function(a){_ds.y(a,"hidden","",a.D);a.removeAttribute("overflow-menu--open")},jV=async function(a){return(await _ds.u()).isTouchEnabled()||!a.hasAttribute("generated-tab-menu")?!1:!0},kV=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&
(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.L(hV,{di:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),null==a||a.appendChild(c)))}},lV=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(e=>e.removeAttribute("active"));d.forEach(e=>_ds.y(a,"hidden","",e));b=b.find(e=>e.getAttribute("column-id")===
c);d=d.find(e=>e.getAttribute("column-id")===c);b&&d&&(_ds.y(a,"active","",b),d.removeAttribute("hidden"))},zV=class extends _ds.A{constructor(){super();this.eventHandler=new _ds.E;this.j=new _ds.E;this.H=new _ds.hk(()=>{xV(this)},20);this.K=null;this.F=!1;this.G=0;this.D=this.h=null;this.J=0;this.v=[];this.C=null;_ds.Gg(this,this.o`active`,this.o`aria-expanded`,this.o`aria-selected`,this.o`collapsed`,this.o`column-id`,this.o`connected`,this.o`dropdown`,this.o`dropdown-full`,this.o`dropdown--open`,
this.o`dropdown-transition`,this.o`hidden`,this.o`no-overflow`,this.o`overflow-menu--open`,this.o`overflow-tab`,this.o`render-hidden`,this.o`scrollbars`)}disconnectedCallback(){_ds.F(this.eventHandler);_ds.F(this.j)}connectedCallback(){this.F||(iV(this),this.F=!0);_ds.y(this,"connected","");if(!this.hasAttribute("no-overflow")){_ds.y(this,"collapsed","",this.h);this.J=nV(this,this.h);var a;null==(a=this.h)||a.removeAttribute("collapsed");wV(this);xV(this)}mV(this)}};
zV.prototype.connectedCallback=zV.prototype.connectedCallback;zV.prototype.disconnectedCallback=zV.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",zV)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
