(function(_ds){var window=this;var dL=function(a){return!a.classList.contains("material-icons")},lL=async function(a,b){await DevsiteApp.whenReady();const c=_ds.B();var d=DevsiteApp.getInsecureHost();b=b.X;if(b.origin===c.origin||!d||b.origin===d){try{var e=_ds.Je(_ds.dl,b.data)}catch(g){return}d=_ds.pe(e,1,0);if(4===d)eL(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:fL(e,f);break;case 8:gL(b,e,c);break;case 1:hL(b,e,c);break;case 6:case 7:iL(d,c,e);break;case 9:jL(a,
e);break;case 10:kL(e,c)}}}},pL=function(a){a.v=a.querySelector(".devsite-article-body");a.v&&mL(a);a.h&&a.h.disconnect();a.j.clear();nL(a);if(!document.body.hasAttribute("dark-theme")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.v&&(b=Array.from(a.v.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.j.clear();a.j=new Set(c);if(_ds.B().hash){c=new _ds.bC;for(const d of a.j)_ds.aC(c,d,dL)}else oL(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},nL=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));b.parentNode&&b.parentNode.insertBefore(c,b);c.appendChild(b)}})},eL=async function(a,b){var c=qL(a,b.source);c&&(a="goog_"+_ds.nh++,c.setAttribute("name",a),c=_ds.gl(3),a=_ds.He(c,2,a),(b=b.source)&&b.postMessage(_ds.Ke(a),"*"))},fL=async function(a,b){const c=_ds.zh(document).y,d=_ds.De(a,4);a=_ds.De(a,3);b=_ds.Nh(b);d&&b.setAttribute("width",`${d}px`);a&&b.setAttribute("height",`${a}px`);
window.requestAnimationFrame(()=>{window.scrollTo(_ds.zh(document).x,c)})},gL=async function(a,b,c){b=_ds.hl(_ds.gl(8),_ds.x(b,8));c=_ds.He(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.Ke(c),"*")},hL=async function(a,b,c){b=_ds.hl(_ds.gl(2),_ds.x(b,8));c=_ds.He(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.Ke(c),"*")},iL=async function(a,b,c){const d=c.Ha();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;6===a?window.history.pushState({},
d,b):window.history.replaceState({},d,b)},jL=async function(a,b){const c=_ds.x(b,9);b=JSON.parse(_ds.x(b,10));"cloudtrackEvent"===c&&b?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:b},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:b,bubbles:!0}))},kL=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?
DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},qL=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.Oh(d)===b&&(c=d)});return c},mL=function(a){"full"===document.body.getAttribute("layout")&&(a=a.v.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},oL=function(a,b){a.h&&b.forEach(c=>{a.h.observe(c)})},rL=
class extends _ds.A{constructor(){super();this.C=new _ds.E;this.D=new _ds.E;this.j=new Set;this.h=null;"IntersectionObserver"in window&&(this.h=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&(a=b.target,_ds.aC(new _ds.bC,a,dL),this.j.delete(a),this.h.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.C.listen(window,"message",a=>lL(this,a));pL(this)}disconnectedCallback(){this.h&&this.h.disconnect();this.j.clear();_ds.F(this.C);_ds.F(this.D)}Wa(a){a&&([".devsite-article",
".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>{_ds.Jg(this,this.querySelector(b),a.querySelector(b))}),pL(this))}};rL.prototype.updateContent=rL.prototype.Wa;rL.prototype.disconnectedCallback=rL.prototype.disconnectedCallback;rL.prototype.connectedCallback=rL.prototype.connectedCallback;try{window.customElements.define("devsite-content",rL)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
