(function(_ds){var window=this;var LK=function(){let a;a='<div class="devsite-code-buttons-container" role="group" aria-label="'+_ds.Lw("Action buttons");return(0,_ds.N)(a+'"></div>')},MK=function(a){a=a.label;return(0,_ds.N)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.P(a)+'" data-title="'+_ds.P(a)+'"></button>')},NK=function(a){a=
a.label;return(0,_ds.N)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.P(a)+'" data-title="'+_ds.P(a)+'"></button>')},OK=function(a){var b=a.label;return(0,_ds.N)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+
_ds.P(a.nm)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.P(b)+'" data-title="'+_ds.P(b)+'"></button>')},PK=function(a){a=a.label;return(0,_ds.N)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.P(a)+'" data-title="'+_ds.P(a)+'"></button>')};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(K){return K.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;")}function b(K,Q,ja){switch(K.nodeType){case 1:var ca=K.tagName.toLowerCase();Q.push("<",ca);var na=K.attributes,La=na.length;if(La){if(ja){for(var Ga=[],sa=La;0<=--sa;)Ga[sa]=na[sa];Ga.sort(function(qa,Ia){return qa.name<Ia.name?-1:qa.name===Ia.name?0:1});na=Ga}for(sa=0;sa<La;++sa)Ga=na[sa],Ga.specified&&Q.push(" ",Ga.name.toLowerCase(),'="',Ga.value.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;").replace(z,
"&quot;"),'"')}Q.push(">");for(na=K.firstChild;na;na=na.nextSibling)b(na,Q,ja);!K.firstChild&&/^(?:br|link|img)$/.test(ca)||Q.push("</",ca,">");break;case 3:case 4:Q.push(a(K.nodeValue))}}function c(K){function Q(U){if("\\"!==U.charAt(0))return U.charCodeAt(0);switch(U.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(U.substring(2),16)||U.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(U.substring(1),
8);default:return U.charCodeAt(1)}}function ja(U){if(32>U)return(16>U?"\\x0":"\\x")+U.toString(16);U=String.fromCharCode(U);if("\\"===U||"-"===U||"["===U||"]"===U)U="\\"+U;return U}function ca(U){var V=U.substring(1,U.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));U=[];for(var R=[],xa="^"===V[0],Y=xa?1:0,ta=V.length;Y<ta;++Y){var da=V[Y];switch(da){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":U.push(da);
continue}da=Q(da);if(Y+2<ta&&"-"===V[Y+1]){var Qa=Q(V[Y+2]);Y+=2}else Qa=da;R.push([da,Qa]);65>Qa||122<da||(65>Qa||90<da||R.push([Math.max(65,da)|32,Math.min(Qa,90)|32]),97>Qa||122<da||R.push([Math.max(97,da)&-33,Math.min(Qa,122)&-33]))}R.sort(function(Pb,Bd){return Pb[0]-Bd[0]||Bd[1]-Pb[1]});V=[];da=[NaN,NaN];for(Y=0;Y<R.length;++Y)ta=R[Y],ta[0]<=da[1]+1?da[1]=Math.max(da[1],ta[1]):V.push(da=ta);R=["["];xa&&R.push("^");R.push.apply(R,U);for(Y=0;Y<V.length;++Y)ta=V[Y],R.push(ja(ta[0])),ta[1]>ta[0]&&
(ta[1]+1>ta[0]&&R.push("-"),R.push(ja(ta[1])));R.push("]");return R.join("")}function na(U){for(var V=U.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),R=V.length,xa=[],Y=0,ta=0;Y<R;++Y){var da=V[Y];"("===da?++ta:"\\"===da.charAt(0)&&(da=+da.substring(1))&&da<=ta&&(xa[da]=-1)}for(Y=1;Y<xa.length;++Y)-1===xa[Y]&&(xa[Y]=++La);for(ta=Y=0;Y<R;++Y)da=V[Y],"("===da?(++ta,
void 0===xa[ta]&&(V[Y]="(?:")):"\\"===da.charAt(0)&&(da=+da.substring(1))&&da<=ta&&(V[Y]="\\"+xa[ta]);for(ta=Y=0;Y<R;++Y)"^"===V[Y]&&"^"!==V[Y+1]&&(V[Y]="");if(U.ignoreCase&&Ga)for(Y=0;Y<R;++Y)da=V[Y],U=da.charAt(0),2<=da.length&&"["===U?V[Y]=ca(da):"\\"!==U&&(V[Y]=da.replace(/[a-zA-Z]/g,function(Qa){Qa=Qa.charCodeAt(0);return"["+String.fromCharCode(Qa&-33,Qa|32)+"]"}));return V.join("")}for(var La=0,Ga=!1,sa=!1,qa=0,Ia=K.length;qa<Ia;++qa){var Ja=K[qa];if(Ja.ignoreCase)sa=!0;else if(/[a-z]/i.test(Ja.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,
""))){Ga=!0;sa=!1;break}}var Da=[];qa=0;for(Ia=K.length;qa<Ia;++qa){Ja=K[qa];if(Ja.global||Ja.multiline)throw Error(""+Ja);Da.push("(?:"+na(Ja)+")")}return new RegExp(Da.join("|"),sa?"gi":"g")}function d(K){var Q=0;return function(ja){for(var ca=null,na=0,La=0,Ga=ja.length;La<Ga;++La)switch(ja.charAt(La)){case "\t":ca||(ca=[]);ca.push(ja.substring(na,La));na=K-Q%K;for(Q+=na;0<=na;na-=16)ca.push("                ".substring(0,na));na=La+1;break;case "\n":Q=0;break;default:++Q}if(!ca)return ja;ca.push(ja.substring(na));
return ca.join("")}}function e(K,Q,ja,ca){Q&&(K={source:Q,Yi:K},ja(K),ca.push.apply(ca,K.jj))}function f(K,Q){var ja={},ca;(function(){for(var Ga=K.concat(Q),sa=[],qa={},Ia=0,Ja=Ga.length;Ia<Ja;++Ia){var Da=Ga[Ia],U=Da[3];if(U)for(var V=U.length;0<=--V;)ja[U.charAt(V)]=Da;Da=Da[1];U=""+Da;qa.hasOwnProperty(U)||(sa.push(Da),qa[U]=null)}sa.push(/[\0-\uffff]/);ca=c(sa)})();var na=Q.length,La=function(Ga){for(var sa=Ga.Yi,qa=[sa,"pln"],Ia=0,Ja=Ga.source.match(ca)||[],Da={},U=0,V=Ja.length;U<V;++U){var R=
Ja[U],xa=Da[R],Y=void 0;if("string"===typeof xa)var ta=!1;else{var da=ja[R.charAt(0)];if(da)Y=R.match(da[1]),xa=da[0];else{for(ta=0;ta<na;++ta)if(da=Q[ta],Y=R.match(da[1])){xa=da[0];break}Y||(xa="pln")}!(ta=5<=xa.length&&"lang-"===xa.substring(0,5))||Y&&"string"===typeof Y[1]||(ta=!1,xa="src");ta||(Da[R]=xa)}da=Ia;Ia+=R.length;if(ta){ta=Y[1];var Qa=R.indexOf(ta),Pb=Qa+ta.length;Y[2]&&(Pb=R.length-Y[2].length,Qa=Pb-ta.length);xa=xa.substring(5);e(sa+da,R.substring(0,Qa),La,qa);e(sa+da+Qa,ta,l(xa,ta),
qa);e(sa+da+Pb,R.substring(Pb),La,qa)}else qa.push(sa+da,xa)}Ga.jj=qa};return La}function g(K){var Q=[],ja=[];K.tripleQuotedStrings?Q.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):K.multiLineStrings?Q.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):Q.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,
null,"\"'"]);K.verbatimStrings&&ja.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var ca=K.hashComments;ca&&(K.cStyleComments?(1<ca?Q.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):Q.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),ja.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):Q.push(["com",/^#[^\r\n]*/,null,"#"]));K.cStyleComments&&(ja.push(["com",/^\/\/[^\r\n]*/,
null]),ja.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));K.regexLiterals&&ja.push(["lang-regex",new RegExp("^"+p+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);K=K.keywords.replace(/^\s+|\s+$/g,"");K.length&&ja.push(["kwd",new RegExp("^(?:"+K.replace(/\s+/g,"|")+")\\b"),null]);Q.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);ja.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],
["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(Q,ja)}function h(K){function Q(ze){if(ze>qa){Ia&&Ia!==Ja&&(sa.push("</span>"),Ia=null);!Ia&&Ja&&(Ia=Ja,sa.push('<span class="',Ia,'">'));var fl=a(V(ja.substring(qa,ze))).replace(da?xa:R,"$1&#160;");da=ta.test(fl);sa.push(fl.replace(Y,el));qa=ze}}var ja=K.source,ca=K.Fm,na=K.jj,La=K.Hj,Ga=K.bk,sa=[],qa=0,Ia=null,Ja=null,Da=0,U=0,V=
d(window.PR_TAB_WIDTH),R=/([\r\n ]) /g,xa=/(^| ) /gm,Y=/\r\n?|\n/g,ta=/[ \r\n]$/,da=!0,Qa=window._pr_isIE6();Ga=Qa?Ga&&"PRE"===Ga.tagName?6===Qa?"&#160;\r\n":7===Qa?"&#160;<br />\r":8===Qa?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(La){var Pb=[];for(Qa=0;10>Qa;++Qa)Pb[Qa]=Ga+'</li><li class="L'+Qa+'">';var Bd="number"===typeof La?La-1:0;sa.push('<ol class="linenums"><li class="L',Bd%10,'"');Bd&&sa.push(' value="',Bd+1,'"');sa.push(">");var el=function(){var ze=Pb[++Bd%10];return Ia?"</span>"+
ze+'<span class="'+Ia+'">':ze}}else el=Ga;for(;;)if(Da<ca.length&&(U<na.length?ca[Da]<=na[U]:1))Q(ca[Da]),Ia&&(sa.push("</span>"),Ia=null),sa.push(ca[Da+1]),Da+=2;else if(U<na.length)Q(na[U]),Ja=na[U+1],U+=2;else break;Q(ja.length);Ia&&sa.push("</span>");La&&sa.push("</li></ol>");K.Hh=sa.join("")}function k(K,Q){for(var ja=Q.length;0<=--ja;){var ca=Q[ja];Ha.hasOwnProperty(ca)?"console"in window&&console.warn("cannot override language handler %s",ca):Ha[ca]=K}}function l(K,Q){K&&Ha.hasOwnProperty(K)||
(K=/^\s*</.test(Q)?"default-markup":"default-code");return Ha[K]}function m(K){var Q=K.$j,ja=K.zj;K.Hh=Q;try{var ca=Q.match(Ba);Q=[];var na=0,La=[];if(ca)for(var Ga=0,sa=ca.length;Ga<sa;++Ga){var qa=ca[Ga];if(1<qa.length&&"<"===qa.charAt(0)){if(!ia.test(qa))if(wa.test(qa))Q.push(qa.substring(9,qa.length-3)),na+=qa.length-12;else if(ma.test(qa))Q.push("\n"),++na;else if(0<=qa.indexOf("nocode")&&qa.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Ia=
qa.match(Ya)[2],Ja=1;var Da=Ga+1;a:for(;Da<sa;++Da){var U=ca[Da].match(Ya);if(U&&U[2]===Ia)if("/"===U[1]){if(0===--Ja)break a}else++Ja}Da<sa?(La.push(na,ca.slice(Ga,Da+1).join("")),Ga=Da):La.push(na,qa)}else La.push(na,qa)}else{Ja=qa;var V=Ja.indexOf("&");if(0>V)var R=Ja;else{for(--V;0<=(V=Ja.indexOf("&#",V+1));){var xa=Ja.indexOf(";",V);if(0<=xa){var Y=Ja.substring(V+3,xa),ta=10;Y&&"x"===Y.charAt(0)&&(Y=Y.substring(1),ta=16);var da=parseInt(Y,ta);isNaN(da)||(Ja=Ja.substring(0,V)+String.fromCharCode(da)+
Ja.substring(xa+1))}}R=Ja.replace(C,"<").replace(D,">").replace(T,"'").replace(H,'"').replace(la," ").replace(Z,"&")}Q.push(R);na+=R.length}}var Qa=Q.join("");K.source=Qa;K.Yi=0;K.Fm=La;l(ja,Qa)(K);h(K)}catch(Pb){"console"in window&&console.log(Pb&&Pb.stack?Pb.stack:Pb)}}var p=function(){for(var K="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
Q="(?:^^|[+-]",ja=0;ja<K.length;++ja)Q+="|"+K[ja].replace(/([^=<>:&a-z])/g,"\\$1");return Q+")\\s*"}(),t=/&/g,v=/</g,w=/>/g,z=/"/g,C=/&lt;/g,D=/&gt;/g,T=/&apos;/g,H=/&quot;/g,Z=/&amp;/g,la=/&nbsp;/g,ka=/[\r\n]/g,Aa=null,Ba=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),ia=/^\x3c!--/,wa=/^<!\[CDATA\[/,ma=/^<br\b/i,Ya=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,xb=g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ha={};k(xb,["default-code"]);k(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));k(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);k(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));k(g({keywords:"null true false"}),["json"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);k(g({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);k(g({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);k(g({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);k(g({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);k(g({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);k(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(K,Q,ja){K={$j:K,zj:Q,Hj:ja};m(K);return K.Hh};window.prettyPrint=function(K){function Q(){for(var Ja=
window.PR_SHOULD_USE_CONTINUATION?sa.now()+250:Infinity;qa<ca.length&&sa.now()<Ja;qa++){var Da=ca[qa];if(Da.className&&0<=Da.className.indexOf("prettyprint")){var U=Da.className.match(/\blang-(\w+)\b/);U&&(U=U[1]);for(var V=!1,R=Da.parentNode;R;R=R.parentNode)if(("pre"===R.tagName||"code"===R.tagName||"xmp"===R.tagName)&&R.className&&0<=R.className.indexOf("prettyprint")){V=!0;break}if(!V){R=Da;null===Aa&&(V=document.createElement("PRE"),V.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
Aa=!/</.test(V.innerHTML));if(Aa)if(V=R.innerHTML,"XMP"===R.tagName)V=a(V);else{if("PRE"!==R.tagName&&ka.test(V)){var xa="";R.currentStyle?xa=R.currentStyle.whiteSpace:window.getComputedStyle&&(xa=window.getComputedStyle(R,null).whiteSpace);R=!xa||"pre"===xa}else R=!0;R||(V=V.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{V=[];for(R=R.firstChild;R;R=R.nextSibling)b(R,V);V=V.join("")}V=V.replace(/(?:\r\n?|\n)$/,"");R=Da.className.match(/\blinenums\b(?::(\d+))?/);Ia={$j:V,
zj:U,bk:Da,Hj:R?R[1]&&R[1].length?+R[1]:!0:!1};m(Ia);if(Da=Ia.Hh)if(U=Ia.bk,"XMP"===U.tagName){V=document.createElement("PRE");for(R=0;R<U.attributes.length;++R)xa=U.attributes[R],xa.specified&&("class"===xa.name.toLowerCase()?V.className=xa.value:V.setAttribute(xa.name,xa.value));V.innerHTML=Da;U.parentNode.replaceChild(V,U)}else U.innerHTML=Da}}}qa<ca.length?setTimeout(Q,250):K&&K()}for(var ja=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
ca=[],na=0;na<ja.length;++na)for(var La=0,Ga=ja[na].length;La<Ga;++La)ca.push(ja[na][La]);ja=null;var sa=Date;sa.now||(sa={now:function(){return(new Date).getTime()}});var qa=0,Ia;Q()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:k,sourceDecorator:g,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[window.PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[window.PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[window.PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[window.PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[window.PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],
[window.PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],[window.PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[window.PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[window.PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[window.PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[window.PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);
window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[window.PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\v\f\r "],[window.PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[window.PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[window.PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[window.PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[window.PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[window.PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[window.PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],
[window.PR.PR_LITERAL,/^(?:true|false|null)\b/],[window.PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[window.PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[window.PR.PR_COMMENT,/^\/\/.*/],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[window.PR.PR_STRING,/'.'/],[window.PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[window.PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[window.PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[window.PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),
["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[window.PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[window.PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[window.PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[window.PR.PR_LITERAL,
/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_]\w*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[window.PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[window.PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[window.PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);window.PR.registerLangHandler(window.PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[window.PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[window.PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[window.PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[window.PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[window.PR.PR_KEYWORD,
/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],[window.PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[window.PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[window.PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[window.PR.PR_PLAIN,
/^[$a-zA-Z_][\w$]*/],[window.PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[window.PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[window.PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[window.PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_][\w-]*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[window.PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[window.PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[window.PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[window.PR.PR_LITERAL,/^(?:true|false|nil)\b/,
null],[window.PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[window.PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[window.PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[window.PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[window.PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[window.PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[window.PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[window.PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[window.PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[window.PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[window.PR.PR_PUNCTUATION,/^(?:\[|\])/]]),
["vb","vbs"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[window.PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[window.PR.PR_COMMENT,/^--[^\r\n]*/],[window.PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[window.PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[window.PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[window.PR.PR_LITERAL,
/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],[window.PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[window.PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[window.PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[window.PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[window.PR.PR_PLAIN,
/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[window.PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[window.PR.PR_TYPE,/^[&]\S+/,null,"&"],[window.PR.PR_TYPE,/^!\S*/,null,"!"],[window.PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[window.PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],
[window.PR.PR_PUNCTUATION,/^-/],[window.PR.PR_KEYWORD,/^\w+:[ \r\n]/],[window.PR.PR_PLAIN,/^\w+/]]),["yaml","yml"]);var QK=window;var SK=function(a){a.D&&a.eventHandler.listen(a.D,"click",()=>void a.setAttribute("dark-code",""));a.G&&a.eventHandler.listen(a.G,"click",()=>void a.removeAttribute("dark-code"));a.j&&a.eventHandler.listen(a.j,"click",()=>void RK(a));a.v&&a.eventHandler.listen(a.v,"click",()=>{const b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.MF(c,b):_ds.LF([a],b)})},RK=async function(a){var b=a.querySelector("pre:not(.devsite-copy-hide)");
if(b&&(b=[...b.childNodes],_ds.Dp(document.body,b),a.C)){const c=new _ds.nk;let d;null==(d=a.j)||d.setAttribute("aria-label","Code sample copied to clipboard");_ds.lk(a.eventHandler,a.C,"transitionend",()=>{c.h()});await c.promise;_ds.lk(a.eventHandler,a.C,"transitionend",()=>{let e;null==(e=a.j)||e.setAttribute("aria-label",a.H)})}},TK=class extends _ds.A{constructor(){super(["devsite-snackbar"]);this.C=this.G=this.v=this.D=this.j=this.h=null;this.K=!1;this.H="";this.eventHandler=new _ds.E;this.J=
new _ds.nk;this.F=new _ds.Sl;this.L=new _ds.uA(_ds.yA(_ds.xA()));_ds.Gg(this,(0,_ds.r)`no-toggle`)}static get observedAttributes(){return["dark-code"]}whenReady(){return this.J.promise}async connectedCallback(){var a=await _ds.u();if(!this.K){var b=this.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))this.setAttribute("no-copy",
""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");this.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");var c=b.getAttribute("data-label");this.H=c?`${"Copy code sample"}: ${c}`:"Copy code sample";b.classList.contains("devsite-disable-code-toggle")&&(_ds.y(this,"no-toggle","",this),b.classList.remove("devsite-disable-code-toggle"))}if(b=this.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample"))this.setAttribute("js-fiddle",
""),b.classList.remove("devsite-enable-open-in-jsfiddle"),b.classList.add("devsite-jsfiddle-code-sample");if(this.hasAttribute("js-fiddle")&&b){c=["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"];for(var d of c)b.hasAttribute(`data-${d}`)&&(this.setAttribute(d,`${b.getAttribute(`data-${d}`)}`),b.removeAttribute(`data-${d}`))}this.prettyPrint();this.K=!0}if((d=this.querySelector(".devsite-dark-code-default"))||this.F.get("pref_dark-code"))this.setAttribute("dark-code",""),d&&d.classList.remove("devsite-dark-code-default");
this.J.h();try{await a.intersectionEnterForElement(this)}catch(g){if("IntersectionObserver not supported"!==g.message)return}if(a=this.querySelector(".devsite-code-buttons-container"))this.h=a;else{this.h=_ds.L(LK);if(this.hasAttribute("scope")){this.v=_ds.L(PK,{label:"Open code sample in JSFiddle"});(this.hasAttribute("jsfiddle-label")||this.hasAttribute("jsfiddle-title"))&&this.v.setAttribute("data-label",`${this.getAttribute("jsfiddle-label")||this.getAttribute("jsfiddle-title")}`);var e;null==
(e=this.h)||e.appendChild(this.v)}if(!this.hasAttribute("no-toggle")){this.D=_ds.L(MK,{label:"Dark code theme"});var f;null==(f=this.h)||f.appendChild(this.D);this.G=_ds.L(NK,{label:"Light code theme"});let g;null==(g=this.h)||g.appendChild(this.G)}if(!this.hasAttribute("no-copy")){e=this.getAttribute("data-copy-event-label");f="Click To Copy";e&&(f+=`: ${e}`);this.j=_ds.L(OK,{label:this.H,nm:f});let g;null==(g=this.h)||g.appendChild(this.j)}this.prepend(this.h)}SK(this);this.C=document.querySelector("devsite-snackbar")}async disconnectedCallback(){(await _ds.u()).unregisterIntersectionForElement(this);
this.h&&this.removeChild(this.h);_ds.F(this.eventHandler)}prettyPrint(){var a=[...this.getElementsByClassName("prettyprint")];for(const c of a){c.classList.remove("prettyprint");var b=(a=c.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?a[1]:void 0;let d;a=c.innerHTML;b=null!=(d=b)?d:"";a=a.replace(/(&#39;)/g,"'");a=QK.prettyPrintOne(a,b,void 0);_ds.wc(c,this.L.h(a));c.getElementsByTagName("strong").length&&c.classList.add("devsite-code-highlight")}}async attributeChangedCallback(a,b,c){if("dark-code"===
a&&b!==c&&!this.querySelector(".devsite-dark-code-default"))if(this.hasAttribute("dark-code")){this.F.set("pref_dark-code","1");await _ds.Xi();var d=[...document.querySelectorAll("devsite-code:not([dark-code])")].filter(f=>f!==this);for(var e of d)e.setAttribute("dark-code","")}else{this.F.remove("pref_dark-code");await _ds.Xi();e=[...document.querySelectorAll("devsite-code[dark-code]")];for(d of e)d.removeAttribute("dark-code")}}};TK.prototype.attributeChangedCallback=TK.prototype.attributeChangedCallback;
TK.prototype.disconnectedCallback=TK.prototype.disconnectedCallback;TK.prototype.connectedCallback=TK.prototype.connectedCallback;TK.prototype.whenReady=TK.prototype.whenReady;try{window.customElements.define("devsite-code",TK)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
