(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var PN=_ds.Sg(function(){return!_ds.Gd||0<=_ds.xd(_ds.cG,9)}),QN=_ds.Sg(function(){return _ds.Kd||_ds.Hd||_ds.Jd&&0<=_ds.xd(_ds.cG,10)||_ds.Gd&&0<=_ds.xd(_ds.cG,10)}),SN=function(a,b){PN()&&(b=QN()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.rk(a,RN(),b))},RN=_ds.Sg(function(){return _ds.Gd&&9==_ds.be?"-ms-transform":"transform"});var VN=function(a){a.j=TN(a,".devsite-top-logo-row-wrapper-wrapper");a.h=TN(a,".devsite-collapsible-section");a.v=TN(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);UN(a)},UN=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.F&&(_ds.rk(b,"transform",`translate3d(0, -${a.offset}px, 0)`),WN(a),a.F=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},XN=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.F(a.G);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.dh(b.offsetWidth,b.offsetHeight);b=new _ds.dh(c.offsetWidth,c.offsetHeight);var f=_ds.Kk(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.rk(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});SN(c,a.hasAttribute("search-active")?0:e);_ds.lk(a.G,d,_ds.Ve,()=>{const m=a.querySelector("devsite-search"),p=a.querySelector(".devsite-search-background");
p&&(p.style.opacity="0");m&&(m.removeAttribute("transition"),SN(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(PN()){var m=QN()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.rk(d,RN(),m)}SN(c,k)})}},YN=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Xi(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},$N=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.X;_ds.Yh(b.target,null,"devsite-top-logo-row-middle",void 0)&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>ZN(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{ZN(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},aO=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},WN=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},ZN=function(a){window.requestAnimationFrame(()=>
a.K.h())},TN=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},bO=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},cO=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Jg(a,c,b))},dO=class extends _ds.A{constructor(){super(...arguments);this.eventHandler=new _ds.E;this.F=
-1;this.G=new _ds.E;this.D=0;this.H=new MutationObserver(()=>VN(this));this.K=new _ds.hk(()=>{VN(this);WN(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.j=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;UN(this);break;case "search-active":XN(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),YN(this,a)}}connectedCallback(){$N(this);aO(this);WN(this);VN(this);this.H.observe(this,{childList:!0,subtree:!0});UN(this);const a=_ds.B();this.authUser=_ds.yi(_ds.zi(a.href),"authuser")}disconnectedCallback(){_ds.F(this.eventHandler);this.H.disconnect()}C(){return this.j+this.h-this.offset}J(){return this.j+this.h}Wa(a){this.updated=!1;if(a){cO(this,a,".devsite-header-upper-tabs");
cO(this,a,".devsite-collapsible-section");cO(this,a,".devsite-product-name-wrapper");cO(this,a,"devsite-language-selector");cO(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&bO(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(bO(c,b),c=_ds.B(),c=_ds.yi(_ds.zi(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Jg(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Jg(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Fh(this),this.appendChild(a));aO(this);ZN(this)}};try{window.customElements.define("devsite-header",dO)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
